"""add is_active column

Revision ID: 11a13f540674
Revises: d20c7d752fdf
Create Date: 2026-01-21 22:27:05.247206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11a13f540674'
down_revision: Union[str, Sequence[str], None] = 'd20c7d752fdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('coin', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('balances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_balances_coin'), ['coin'], unique=False)
        batch_op.create_index(batch_op.f('ix_balances_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_balances_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('balances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_balances_user_id'))
        batch_op.drop_index(batch_op.f('ix_balances_id'))
        batch_op.drop_index(batch_op.f('ix_balances_coin'))

    op.drop_table('balances')
    # ### end Alembic commands ###
